version: "3.8"

name: 'id-transformation-issue'

services:
  pg:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5434
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql